### ISSUE TITLE
implementation 'com.android.support:appcompat-v7:27.1.1' is creating issues

### ISSUE THREAD

**Issue by Bharatsingh049** [andremion/CounterFab#15]
implementation 'com.android.support:appcompat-v7:27.1.1'
is not compatible with    implementation 'com.github.andremion:counterfab:1.0.1'
I got an error

Program type already present: android.support.design.widget.CoordinatorLayout$Behavior
Message{kind=ERROR, text=Program type already present: android.support.design.widget.CoordinatorLayout$Behavior, sources=[Unknown source file], tool name=Optional.of(D8)}

please help I have to finish it soon

**Comment by andremion** [comment]
Hi @Bharatsingh049 
Add this to your gradle `implementation 'com.android.support:design:27.1.1'`
This will force your `design` dependency to use the same version of your `appcompat` dependency.
Let me know if it works.

**Comment by andremion** [comment]
Close due no response
