### ISSUE TITLE
Changing the counter background color

### ISSUE THREAD

**Issue by ToniNgethe** [andremion/CounterFab#3]
Is there a method of changing the counter background color other than using the default tint color of the floating action bar

**Comment by andremion** [comment]
@ToniNgethe, for now no.
The concept uses the FAB tint color masked with a translucent black.
You can change the FAB tint color by `app:backgroundTint` attribute.

**Comment by juanmarin-co** [comment]
It would be useful to change the color with a attribute in cases where I want to change the fab background color

**Comment by juanmarin-co** [comment]
#7 Here an implementation proposal

**Comment by dawit-abraham** [comment]
any update on this? Is it solved?
