### ISSUE TITLE
Badge showing different background color

### ISSUE THREAD

**Issue by waseem786** [andremion/CounterFab#30]
Hi, when I change the counter badge background color using app:badgeBackgroundColor attribute, always badge color showing a darker color than I selected. 
Example : if I set app:badgeBackgroundColor = "#ffffff", counter icon displaying with a  grey color.
How can I fix this?
Thanks

**Comment by andremion** [comment]
Hi @waseem786 
That behaviour is on proposal by design.
For every color of the badge will have mask to differentiate from the button itself in case of same color.
I will think in changing this behaviour, maybe having this mask as optional

**Comment by waseem786** [comment]
Thanks for the response, I am waiting for the next update :)

**Comment by grAPPfruit** [comment]
The Problem with that is that I cannot set the color that I want to the badge.
Is there a way to turn that off yet?

**Comment by andremion** [comment]
Hi guys!
This release https://github.com/andremion/CounterFab/releases/tag/v1.2.2 contains what you want.
Now that badge color mask is only used when no badge color is defined.
Enjoy it 🙂
