### ISSUE TITLE
How to configure for scroll recycler view scroll behavior

### ISSUE THREAD

**Issue by waseem786** [andremion/CounterFab#31]
I added CounterFab over a recycler view.
What I want to know is, how can I configure CounterFab to hide when scroll the recycler view? Anyone know any trick? or any methods?

**Comment by andremion** [comment]
I used that behaviour here -> https://github.com/andremion/Louvre
You need to use `CoordinatorLayout` as the parent container of the `RecyclerView` and set 
 the `app:layout_behavior` attribute of `CounterFab` as some behaviour customized by you (see [com.andremion.louvre.util.FabBehavior](https://github.com/andremion/Louvre/blob/development/louvre/src/main/java/com/andremion/louvre/util/FabBehavior.java))
