### ISSUE TITLE
Background has some error render at bottom

### ISSUE THREAD

**Issue by nguyenhuutinh** [andremion/CounterFab#33]
Hi, I tried use it as the service icon but the background has some error. do you know why?

![device-2019-05-06-111846](https://user-images.githubusercontent.com/4114159/57205357-bcb01000-6ff0-11e9-865d-de27d68bf096.png)

**Comment by andremion** [comment]
Hi @nguyenhuutinh ,
Can you send me more details about this?
Such as:
- Which device?
- Android version?
- Snippet of your CounterFab xml setup?
Thanks

**Comment by andremion** [comment]
Closed due to no response
