### ISSUE TITLE
Batch Background color resource linking failed

### ISSUE THREAD

**Issue by GauthamAsir** [andremion/CounterFab#34]
app:badgeBackgroundColor & app:badgeTextColor gives "Android resource linking failed"
any fixes ?

**Comment by XamDev19** [comment]
I'm facing the same issue.

**Comment by andremion** [comment]
Could you send me more details about this?
Such as:
- Android version?
- Snippet of your CounterFab xml setup?
- Anything that can help me to understand that issue because I'm not facing it.

Thanks

**Comment by GauthamAsir** [comment]
> Could you send me more details about this?
> Such as:
> 
> * Android version?
> * Snippet of your CounterFab xml setup?
> * Anything that can help me to understand that issue because I'm not facing it.
> 
> Thanks

Thanks For Your Reply, I Upgraded My Gradle Version, and its fixed now.
