### ISSUE TITLE
BadParcelableException still exists in v1.2.2

### ISSUE THREAD

**Issue by shreyashraj** [andremion/CounterFab#37]
<img width="422" alt="Screenshot 2019-12-16 at 12 07 34 PM" src="https://user-images.githubusercontent.com/15965448/70884758-ef959a00-1ffc-11ea-8039-66c63d4f5438.png">
<img width="432" alt="Screenshot 2019-12-16 at 12 07 28 PM" src="https://user-images.githubusercontent.com/15965448/70884759-ef959a00-1ffc-11ea-8914-37cdb814b6b8.png">
<img width="441" alt="Screenshot 2019-12-16 at 12 07 22 PM" src="https://user-images.githubusercontent.com/15965448/70884761-f02e3080-1ffc-11ea-8c2d-532f3512d896.png">

The counter fab is failing in a few version of android still in 1.2.2

**Comment by shreyashraj** [comment]
<img width="1289" alt="Screenshot 2019-12-16 at 12 07 06 PM" src="https://user-images.githubusercontent.com/15965448/70884816-0fc55900-1ffd-11ea-96bc-48c8822b39b0.png">

**Comment by andremion** [comment]
Hi @shreyashraj,
Thanks to let me know.
According to the line of code I see in the print (`CounterFab.java:235`) that is not the latest version. It seams version `1.0.3`.
User may be using old version of your app that is using old version of the library.

**Comment by shreyashraj** [comment]
<img width="408" alt="Screenshot 2019-12-17 at 10 41 32 AM" src="https://user-images.githubusercontent.com/15965448/70966621-d9014880-20b9-11ea-8e09-2c89c367c05e.png">
Though I have replaced it with the latest version, will wait for few more days to see if any crash occurs. Thanks.
