### ISSUE TITLE
Could you please open the class CounterFab ?

### ISSUE THREAD

**Issue by StevenMichael3213** [andremion/CounterFab#38]
If you open the Class CounterFab like below (add the keyword `open` in front of `class`) :

> open class CounterFab @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyleAttr: Int = R.attr.floatingActionButtonStyle
) : FloatingActionButton(context, attrs, defStyleAttr) 

This will make it easy for others to inherit.

**Comment by andremion** [comment]
Sure.
You can also open a PR with that change 🙂

**Comment by StevenMichael3213** [comment]
Ok

**Comment by andremion** [comment]
You didn't need to close that issue. Just opening a PR linked to this :)
